### ISSUE TITLE
add server configuration json

### ISSUE THREAD

**Issue by jakep36** [fluree/server#71]
Allow server configuration so a user running fluree server can manage stuff like open/closed mode, ipfs options, etc. 

For GA we'll target at least getting the option to restrict to only requests with credentials allowing server to be run in an open environment without an API in front.

Further options that we may want to add:
- protecting particular ledgers
- allowing create (or delete) for certain identities
- ...

**Comment by Jackamus29** [comment]
Reference to this ticket was made in Discord:
https://discord.com/channels/896089675511508992/896089675511508995/1258715398723862538

**Comment by aaj3f** [comment]
This work is at least initially complete by fluree/server#78

Additional work for `closed-mode` is described in other tickets, so closing this ticket for now
